### ISSUE TITLE
UniCodeEncodeError when running via console

### ISSUE THREAD

**Issue by steveswinsburg** [hdeweyh/strangerVisions#5]
I ran via the console and it gave a UnicodeEncodeError:
```
reading  data from ../dna/genome
interpreting as a 23andme or exemplar formated data file
done reading data file
reading  data from SNPs_public.csv
done reading possible SNPs

Traceback (most recent call last):
  File "run.py", line 40, in <module>
    console.printTable(items)
  File "/strangerVisions/console.py", line 34, in printTable
    print( self.table.draw() )
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' in position 3299: ordinal not in range(128)
```

That Unicode character is a checkmark, but not sure why it thinks it is in there. Data is here:
https://github.com/steveswinsburg/dna

**Comment by JuanmaMorenoSanchez** [comment]
Also an 'ascii' codec problem here. In my case, it was in the html output runing web.py, and the error says it is decoding, not coding. Did you solve the problem? Thanks!

**Comment by JuanmaMorenoSanchez** [comment]
Found a solution for the Unicode error while running web.py. Simply replace 19# line at the result.html file by this:

`<td>{{ item.description.decode('utf-8') }}</td>`
